### ISSUE TITLE
AE-FF4 (5.0m) and AE-FF5 (7.5m) Payload Fairing not working

### ISSUE THREAD

**Issue by Schopfenheiser** [ChrisAdderley/NearFutureLaunchVehicles#112]
To be more specific, it can't build fairings. Interstage nodes and truss are working but the only problem is the inability to build airstreamed shells.

Not sure if this has something to do with mod conflicts or simply a bug on the mod, it would be a great help if you can diagnose this issue (since I can never fully understand KSP logs at the moment).

[KSP.log](https://github.com/ChrisAdderley/NearFutureLaunchVehicles/files/5436789/KSP.log)

**Comment by ChrisAdderley** [comment]
Please update your KSP version to 1.10.1, the version you're using (1.10.0) has a critical bug that breaks all modded fairings.
