### ISSUE TITLE
Advanced RCS Systems

### ISSUE THREAD

**Issue by ChrisAdderley** [ChrisAdderley/NearFutureLaunchVehicles#15]
Heavy reaction control systems in many flavours:

- Aerodynamic heavy model (4-way)
  - [x] Model
  - [x] Unwrap
  - [x] Texture
  - [x] Configuration
- Orbital heavy model (4-way)
  - [x] Model
  - [x] Unwrap
  - [x] Texture
  - [x] Configuration
- Orbital heavy model (1-way)
  - [x] Model
  - [x] Unwrap
  - [x] Texture
  - [x] Configuration
- Orbital heavy integrated model (?-way)
  - [ ] Model
  - [ ] Unwrap
  - [ ] Texture
  - [ ] Configuration
- Orbital integrated model (?-way)
  - [x] Model
  - [x] Unwrap
  - [x] Texture
  - [x] Configuration

**Comment by ChrisAdderley** [comment]
Descoping heavy integrated model for initial release.

**Comment by Vladimir-csp** [comment]
No 3-ways planned?
