### ISSUE TITLE
Engine Mount config issues

### ISSUE THREAD

**Issue by pand5461** [ChrisAdderley/NearFutureLaunchVehicles#29]
In the config for EX-M25 (cluster-mount-75-1), LOC string got to the bulkheadProfiles instead of tags.

**Comment by ChrisAdderley** [comment]
Resolved for next version.

**Comment by pand5461** [comment]
Found a few other misconfigurations:
cluster-mount-5-1 has stackSymmetry=5 by default (which gets overriden, but got apparent to me when I ported configs to 1.2.2)
cluster-mount-75-2 has stackSymmetry=2 in "Six" mode, which looks inconsistent with other engine mounts.

**Comment by ChrisAdderley** [comment]
a) I can change that.
b) needs to be x3, because of the lower engine mount which has a maximum symmetry of x3.

**Comment by pand5461** [comment]
a) Why not just delete that line (71) at all? Other mounts don't have  that.
b) Oh, didn't notice symmetry is set only once for both lower and upper mounts. Actually, I found x3 more convenient because it allows two different types of engines on the upper mount, or easily disable gimbal on half of the engines.

**Comment by pand5461** [comment]
cluster-mount-5-1's ln. 151 has "a" missing in "addedMass"

**Comment by ChrisAdderley** [comment]
Noted.
