### ISSUE TITLE
CryoTanks compatibility

### ISSUE THREAD

**Issue by pand5461** [ChrisAdderley/NearFutureLaunchVehicles#33]
CryoTanks adds its own fuelSwitch module to all tanks which overrides original modules. However, NFLV's fuel switches remain in the part right-click menu but have no effect.

**Comment by ChrisAdderley** [comment]
I had a look, because this was a key test case. It seems that one tank (the NR-6400, short 5m) tank has misconfiguration, but the rest seem fine... Are they all wrong for you? In which case, logs, modlists, the full pile of things are needed.

**Comment by pand5461** [comment]
Well, looked at it again - the issue isn't there in 1.3, probably new B9 Part Switch only shows the last ModuleB9PartSwitch.
This being said, installation of CryoTanks eliminates the Structural option from the 5m nosecone.

But there is another thing - fuel switch has no effect without CryoTanks installed, tanks always have LF+Ox in them. Comparing CryoTanks and NFLV folders, I see B9_TANK_TYPE definitions missing.

**Comment by ChrisAdderley** [comment]
Ah. Yes, bugs on 1.2.2... I don't really care ;) . You should investigate the MM patch rather than B9, as the patch in CryoTanks removes the other fuel switch. 

Good catch on the other fuel switch thing, the TANK_TYPE names are wrong (well, except for LFO). Do you think anyone would care if I removed the oxidizer only fuel type from the default distribution?

**Comment by pand5461** [comment]
Ah, now I see the "delete any existing fuelSwitch" line in the new CryoTanks version.

And, there are just no tankType fields at all in any of the tank cfgs.
I don't mind against removing oxidizer-only tank type, it doesn't have any use on its own anyway. Then again, no-one noticed that fuel switches don't work at all - looks like nobody really cares.

**Comment by ChrisAdderley** [comment]
I'm an idiot. I'll fix it.

**Comment by ChrisAdderley** [comment]
This should be resolved in the latest release, but I'll leave this open for a bit to catch things
