### ISSUE TITLE
7.5m fairing does not connect to 7.5m fuel parts (EA-F) 

### ISSUE THREAD

**Issue by ktwb** [ChrisAdderley/NearFutureLaunchVehicles#36]
Unable to find pink "Close Fairing" to the base of EA-F tanks when using the 7.5m AE-FF5 Payload Fairing.

Steps to replicate: 

1. Place EA-F Tank of any size. 
2. Place any intervening part to be covered by the fairing. Engine, smaller 2.5m part, etc. 
3. Place fairing underneath to the construction node.
4. Attempt to build fairing. Unable to get blue 'place fairing' completion node to seal to the bottom of the EA-F tank.

![ksp_x64_2017-07-27_10-19-45](https://user-images.githubusercontent.com/30461037/28649132-def77e6c-72b5-11e7-9199-2d698984a1e7.jpg)

Notes:

- Problem is limited only to the EA-F tanks. If any other tank or module is used in step 1, the fairing operates correctly. 
![ksp_x64_2017-07-27_10-20-23](https://user-images.githubusercontent.com/30461037/28649188-3f950136-72b6-11e7-96a0-7272b19fe062.jpg)

- No issue with the 5m (NR-) fuel tank parts; fairing binds correctly to the bottom of them.
![ksp_x64_2017-07-27_10-28-57](https://user-images.githubusercontent.com/30461037/28649213-7db5abc8-72b6-11e7-930e-c85cb158d2bf.jpg)

- Fairings from other mods unable to detect the base of the 7.5m part.

**Comment by ChrisAdderley** [comment]
Thanks for the detailed report. I think that the colliders on the 7.5m parts don't have enough sides and this is confusing the snapping system.

**Comment by ChrisAdderley** [comment]
Confirmed that this is indeed resolved with more collider segments.
