### ISSUE TITLE
7.5m fuel tank capacities

### ISSUE THREAD

**Issue by AccidentalDisassembly** [ChrisAdderley/NearFutureLaunchVehicles#44]
If fuel capacity on the 7.5m tanks (EA-F series) is meant to be proportional to the volume of the tank as a cylinder, all of the fuel values should be multiplied by 1.5 (unless I have some weird patch interfering with the numbers, of course...).

If you compare the 7.5m tanks' volume to 5m tanks of the same height, the 7.5m should carry 2.25x the fuel since the ratio of their volumes will be (all else equal) the ratio of their radii squared : 5^2 = 25, 7.5^2 = 56.25, or 2.25x the volume.

**Comment by ChrisAdderley** [comment]
In testing for next version
