### ISSUE TITLE
NR-T-A 5m nosecone inconsistent tank capacity

### ISSUE THREAD

**Issue by riocrokite** [ChrisAdderley/NearFutureLaunchVehicles#48]
I think there's a typo in the tank config; baseVolume is 25600 and fuel values are in total 6400:

https://cdn.discordapp.com/attachments/206472058228572162/364788286448730132/unknown.png

**Comment by riocrokite** [comment]
update:
apart from that there was a discussion to decrease value of fuel to match volume - in this case -bringing everything down to 6400. IMHO I feel that from the looks the 5m nosecone should have similar capacity to nr-12800 5m tank that is 12800. Visual comparison:

![image](https://user-images.githubusercontent.com/9766897/31133146-f27d48fc-a85e-11e7-86ad-c0919b3f18ed.png)

![image](https://user-images.githubusercontent.com/9766897/31133119-e3634510-a85e-11e7-8d6a-2facdb928ff4.png)

**Comment by ChrisAdderley** [comment]
Fixed for next version
