### ISSUE TITLE
5m to 3.75m adapter, short (Fuel Volume Error) 

### ISSUE THREAD

**Issue by I-S-E** [ChrisAdderley/NearFutureLaunchVehicles#50]
Referencing 
`PART
{
	name = fueltank-adapter-5-375-2` 

I noticed that the amount of Liquid-Fuel, and Oxidizer was said to add up to 2600 as base volume, when it should add up to 3770. 
2340 + 1430 = 3770 but 

"baseVolume" has it added up to 

baseVolume = 2600

```// Resources
    RESOURCE
    {
        name = LiquidFuel
        amount = 2340
        maxAmount = 2340
    }
    RESOURCE
    {
        name = Oxidizer
        amount = 1430
        maxAmount =  1430
    }
MODULE
    {
        name = ModuleB9PartSwitch
        moduleID = fuelSwitch
        switcherDescription = #LOC_NFLaunchVehicles_switcher_fuel_title
        baseVolume = 2600```

**Comment by ChrisAdderley** [comment]
Checked, 2600 is the correct value. The LF value is the error, should be 1170.
