### ISSUE TITLE
Cluster mounts coorientation

### ISSUE THREAD

**Issue by Vladimir-csp** [ChrisAdderley/NearFutureLaunchVehicles#54]
When EX-M9 cluster is configured with 3x3 lower and upper mounts, they have unoptimal coorientation.
Looking from the bottom, please rotate lower 3x group 30 degrees clockwise and upper 6x group 30 degrees anywise.
Also, NR-M4 and NR-M6 in 3x mode are laterally asymmetrical (rotated 30 degrees)

**Comment by ChrisAdderley** [comment]
A picture of what you mean would be helpful

**Comment by Vladimir-csp** [comment]
![3x3](https://user-images.githubusercontent.com/4061903/34061626-1c20941e-e1fa-11e7-840e-ae75b671756d.png)
The lower assembly here is not aligned with with the upper and is not laterally symmetrical. Rotate it 30 degrees clockwise to fix.

![3x6 png](https://user-images.githubusercontent.com/4061903/34061732-8bf5e5fa-e1fa-11e7-826f-767a6bb0f159.jpg)
Assuming you've rotated the lower assembly, it is now misaligned with 6x upper assembly. Rotate the upper assembly 30 degrees to fix it.

**Comment by Vladimir-csp** [comment]
Here are the transformations:
![tf](https://user-images.githubusercontent.com/4061903/34062226-7d4d9a5a-e1fc-11e7-8ad1-b0ca7b783e7c.png)

**Comment by ChrisAdderley** [comment]
Cool I'll look at it at some point.

**Comment by ChrisAdderley** [comment]
Resolved for 1.1.4
