### ISSUE TITLE
Error in fueltank-75-1.cfg

### ISSUE THREAD

**Issue by BararQ** [ChrisAdderley/NearFutureLaunchVehicles#57]
Hi, 
Got an error saying volume was not defined and could not switch the tank contents. It looks it was not properly defined.

	MODULE
	{
		name = ModuleB9PartSwitch
		moduleID = fuelSwitch
		switcherDescription = #LOC_NFLaunchVehicles_switcher_fuel_title

		volume = 115200
		SUBTYPE
		{
			name = LFO
			tankType = LFOX
			title = #LOC_NFLaunchVehicles_switcher_fuel_variant-lfo
			addedCost = -50616

		}
		SUBTYPE
		{
			name = LF
			tankType = LF
			title = #LOC_NFLaunchVehicles_switcher_fuel_variant-lf
			addedCost = -50616
		}
	}

It should be baseVolume not volume according to all the other configs. When I make the change in the config below, tank switching works again.

	MODULE
	{
		name = ModuleB9PartSwitch
		moduleID = fuelSwitch
		switcherDescription = #LOC_NFLaunchVehicles_switcher_fuel_title
		baseVolume = 115200

		SUBTYPE
		{
			name = LFO
			tankType = LFOX
			title = #LOC_NFLaunchVehicles_switcher_fuel_variant-lfo
			addedCost = -50616

		}
		SUBTYPE
		{
			name = LF
			tankType = LF
			title = #LOC_NFLaunchVehicles_switcher_fuel_variant-lf
			addedCost = -50616
		}
	}

I downloaded the latest version from CKAN and Spacedock. They both showed this error.
Edited to remove the bold, it just showed as **.

**Comment by ChrisAdderley** [comment]
This has been fixed in dev for a while, I just haven't had time to release it yet.
