### ISSUE TITLE
Missing } in fueltank-adapter-5-375-2.cfg

### ISSUE THREAD

**Issue by BararQ** [ChrisAdderley/NearFutureLaunchVehicles#58]
Hi,

In the fueltank-adapter-5-375-2.cfg it looks like a } is missing.

	// Resources
	RESOURCE
	{
		name = LiquidFuel
		amount = 1170
		maxAmount = 1170
	RESOURCE
	{
		name = Oxidizer
		amount = 1430
		maxAmount =  1430
	}

The } is missing for LiquidFuel, so B9 partswitch would not work and the adapter was stuck with 1170 LiquidFuel.

	// Resources
	RESOURCE
	{
		name = LiquidFuel
		amount = 1170
		maxAmount = 1170
         }     
	RESOURCE
	{
		name = Oxidizer
		amount = 1430
		maxAmount =  1430
	}

I downloaded the latest version from CKAN and Spacedock. They both showed this error.

**Comment by ChrisAdderley** [comment]
This has been fixed in dev for a while, I just haven't had time to release it yet.
