### ISSUE TITLE
NFLV 2.0.0 engines incorrect smokes vector

### ISSUE THREAD

**Issue by HorusAK** [ChrisAdderley/NearFutureLaunchVehicles#95]
Looks like the following engines have wrong vector for smokes:
KR-1E-V "Angora"
KR-76 "Lynx"
KR-84 "Ocelot"
KS-107 "Porpoise"
KS-10AJ "Walrus"
KS-160 "Orca"
KS-1M "Otter"
KS-600AJ "Manatee"

It's pointed sideways.

**Comment by iGGnite** [comment]
I can confirm this issue
![screenshot710](https://user-images.githubusercontent.com/36937528/80863159-a7f56f00-8c7a-11ea-8580-e651ad4b960a.png)
